# Generated by Django 6.0.1 on 2026-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_telegramconfirmation_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
